### PR TITLE
Add ability to generate linux tests

### LINKED ISSUE #29: Generate Linux Tests
I use Ice to manage my various Swift Package Manager projects. This includes testing them using `ice test`. However, when I want to generate Linux tests, I am forced to do:
```bash
swift test --generate-linuxmain
```
It would be great if Ice could generate Linux tests (like `ice test --generate`) so I don't need to switch back and forth.

Maybe Ice could remove the existing files so that it doesn't stop due to the name of a test method changing. This could be optional.

### PR DESCRIPTION
**Pull request by Samasaur1**
As I said in #29, I really like using Ice (so thank you for making it!), but I was missing the ability to generate Linux tests.

That's what this PR adds. You can now do any of the following:
```bash
ice generate-tests
ice test -g
ice test --generate
```
in addition to:
```bash
swift test --generate-linuxmain
```

My only question is whether there should be a "force" mode (probably only for `ice generate-tests`) that removes the preexisting XCTestManifest files so that they don't conflict or fail to build if test names are changed. Either way, this PR closes #29.

### CODE REVIEW

**Comment by Samasaur1** [comment]
Okay, 3b46af8 changes the name of the generation commands and removes the short flag, so now you can do these:
```bash
ice generate-test-list
ice test --generate-list
```
***
As for the file removal, that's what I would prefer, and it's what I would use. However,
```bash
swift test --generate-linuxmain
```
generates the extensions to the test classes *in the `XCTestManifests` file*, as opposed to in the file for each test class (which is how the tests are generated using `swift package init`).

Here's an example:
### Generated on `init`
*`Tests/LinuxMain.swift`*
```swift
import XCTest

import ExampleTests

var tests = [XCTestCaseEntry]()
tests += ExampleTests.allTests()
XCTMain(tests)
```
*`Tests/ExampleTests/XCTestManifests.swift`*
```swift
import XCTest

#if !os(macOS)
public func allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExampleTests.allTests),
    ]
}
#endif
```
*`Tests/ExampleTests/ExampleTests`*
```swift
import XCTest
@testable import Example

final class ExampleTests: XCTestCase {
    func testExample() {
        // This is an example of a functional test case.
        // Use XCTAssert and related functions to verify your tests produce the correct
        // results.
        XCTAssertEqual(Example().text, "Hello, World!")
    }

    static var allTests = [
        ("testExample", testExample),
    ]
}
```
### Generated with `swift test --generate-linuxmain` (after removing the previous files and static var in ExampleTests)
*`Tests/LinuxMain.swift`*
```swift
import XCTest

import ExampleTests

var tests = [XCTestCaseEntry]()
tests += ExampleTests.__allTests()

XCTMain(tests)
```
*`Tests/ExampleTests/XCTestManifests.swift`*
```swift
import XCTest

extension ExampleTests {
    static let __allTests = [
        ("testExample", testExample),
    ]
}

#if !os(macOS)
public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExampleTests.__allTests),
    ]
}
#endif
```
*`Tests/ExampleTests/ExampleTests.swift`*
```swift
import XCTest
@testable import Example

final class ExampleTests: XCTestCase {
    func testExample() {
        // This is an example of a functional test case.
        // Use XCTAssert and related functions to verify your tests produce the correct
        // results.
        XCTAssertEqual(Example().text, "Hello, World!")
    }
}
```
***
As you can see, it's the same thing, but they are moved around. The biggest problem that I can see is that the `static var allTests` could be anywhere in the `ExampleTests.swift` file, and I don't know how to find it

**Comment by Samasaur1** [comment]
@jakeheis What do you think about this?

**Comment by jakeheis** [comment]
I think it should be sufficient to just remove the `XCTestManifests.swift` files. The generated test list uses underscores so it'll never conflict with the initial `allTests` var created on init, so it's not a priority to find and remove that var; `ice generate-test-list` can still work just fine even if that list is left around. It'll be up to the user to eventually delete that initial list, but after they do that by removing XCTestManifests we can be sure changing a test name will not cause any issues.

**Comment by Samasaur1** [comment]
Alright, I had it delete both the `XCTestManifests.swift` file and the `LinuxMain.swift` file, though it probably only needs to delete the `XCTestManifests` file.

**Comment by jakeheis** [comment]
Thanks for your contribution!

**Comment by jakeheis** [comment]
Release as `0.7.2`!

**Pull request merged**
